//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication14.Myservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddBooksToMarOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteBookFromMarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBookToLibOperationCompleted;
        
        private System.Threading.SendOrPostCallback IssueBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowAllReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteBookFromLibOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback forgetpasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback isvaliduserOperationCompleted;
        
        private System.Threading.SendOrPostCallback isvalidAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetpasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowAllBooksLibOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowAllBooksMarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchBookFromLibOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchBookFromMarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WindowsFormsApplication14.Properties.Settings.Default.WindowsFormsApplication14_Myservice_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddBooksToMarCompletedEventHandler AddBooksToMarCompleted;
        
        /// <remarks/>
        public event DeleteBookFromMarCompletedEventHandler DeleteBookFromMarCompleted;
        
        /// <remarks/>
        public event AddBookToLibCompletedEventHandler AddBookToLibCompleted;
        
        /// <remarks/>
        public event IssueBookCompletedEventHandler IssueBookCompleted;
        
        /// <remarks/>
        public event SendReqCompletedEventHandler SendReqCompleted;
        
        /// <remarks/>
        public event ShowAllReqCompletedEventHandler ShowAllReqCompleted;
        
        /// <remarks/>
        public event DeleteBookFromLibCompletedEventHandler DeleteBookFromLibCompleted;
        
        /// <remarks/>
        public event UpdateQuantityCompletedEventHandler UpdateQuantityCompleted;
        
        /// <remarks/>
        public event forgetpasswordCompletedEventHandler forgetpasswordCompleted;
        
        /// <remarks/>
        public event registrationCompletedEventHandler registrationCompleted;
        
        /// <remarks/>
        public event isvaliduserCompletedEventHandler isvaliduserCompleted;
        
        /// <remarks/>
        public event isvalidAdminCompletedEventHandler isvalidAdminCompleted;
        
        /// <remarks/>
        public event resetpasswordCompletedEventHandler resetpasswordCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event ShowAllBooksLibCompletedEventHandler ShowAllBooksLibCompleted;
        
        /// <remarks/>
        public event ShowAllBooksMarCompletedEventHandler ShowAllBooksMarCompleted;
        
        /// <remarks/>
        public event SearchBookFromLibCompletedEventHandler SearchBookFromLibCompleted;
        
        /// <remarks/>
        public event SearchBookFromMarCompletedEventHandler SearchBookFromMarCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AddBooksToMar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddBooksToMar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string price) {
            this.Invoke("AddBooksToMar", new object[] {
                        name,
                        location,
                        price});
        }
        
        /// <remarks/>
        public void AddBooksToMarAsync(string name, string location, string price) {
            this.AddBooksToMarAsync(name, location, price, null);
        }
        
        /// <remarks/>
        public void AddBooksToMarAsync(string name, string location, string price, object userState) {
            if ((this.AddBooksToMarOperationCompleted == null)) {
                this.AddBooksToMarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBooksToMarOperationCompleted);
            }
            this.InvokeAsync("AddBooksToMar", new object[] {
                        name,
                        location,
                        price}, this.AddBooksToMarOperationCompleted, userState);
        }
        
        private void OnAddBooksToMarOperationCompleted(object arg) {
            if ((this.AddBooksToMarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBooksToMarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteBookFromMar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteBookFromMar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location, out bool DeleteBookFromMarResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteBookFromMarResultSpecified) {
            object[] results = this.Invoke("DeleteBookFromMar", new object[] {
                        name,
                        location});
            DeleteBookFromMarResult = ((bool)(results[0]));
            DeleteBookFromMarResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteBookFromMarAsync(string name, string location) {
            this.DeleteBookFromMarAsync(name, location, null);
        }
        
        /// <remarks/>
        public void DeleteBookFromMarAsync(string name, string location, object userState) {
            if ((this.DeleteBookFromMarOperationCompleted == null)) {
                this.DeleteBookFromMarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteBookFromMarOperationCompleted);
            }
            this.InvokeAsync("DeleteBookFromMar", new object[] {
                        name,
                        location}, this.DeleteBookFromMarOperationCompleted, userState);
        }
        
        private void OnDeleteBookFromMarOperationCompleted(object arg) {
            if ((this.DeleteBookFromMarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteBookFromMarCompleted(this, new DeleteBookFromMarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AddBookToLib", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddBookToLib([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Location, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Quantity) {
            this.Invoke("AddBookToLib", new object[] {
                        name,
                        Location,
                        Quantity});
        }
        
        /// <remarks/>
        public void AddBookToLibAsync(string name, string Location, string Quantity) {
            this.AddBookToLibAsync(name, Location, Quantity, null);
        }
        
        /// <remarks/>
        public void AddBookToLibAsync(string name, string Location, string Quantity, object userState) {
            if ((this.AddBookToLibOperationCompleted == null)) {
                this.AddBookToLibOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBookToLibOperationCompleted);
            }
            this.InvokeAsync("AddBookToLib", new object[] {
                        name,
                        Location,
                        Quantity}, this.AddBookToLibOperationCompleted, userState);
        }
        
        private void OnAddBookToLibOperationCompleted(object arg) {
            if ((this.AddBookToLibCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBookToLibCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/IssueBook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IssueBook([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Location, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, out bool IssueBookResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IssueBookResultSpecified) {
            object[] results = this.Invoke("IssueBook", new object[] {
                        name,
                        Location,
                        quantity});
            IssueBookResult = ((bool)(results[0]));
            IssueBookResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IssueBookAsync(string name, string Location, string quantity) {
            this.IssueBookAsync(name, Location, quantity, null);
        }
        
        /// <remarks/>
        public void IssueBookAsync(string name, string Location, string quantity, object userState) {
            if ((this.IssueBookOperationCompleted == null)) {
                this.IssueBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIssueBookOperationCompleted);
            }
            this.InvokeAsync("IssueBook", new object[] {
                        name,
                        Location,
                        quantity}, this.IssueBookOperationCompleted, userState);
        }
        
        private void OnIssueBookOperationCompleted(object arg) {
            if ((this.IssueBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IssueBookCompleted(this, new IssueBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SendReq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendReq([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bookname, out bool SendReqResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SendReqResultSpecified) {
            object[] results = this.Invoke("SendReq", new object[] {
                        username,
                        bookname});
            SendReqResult = ((bool)(results[0]));
            SendReqResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SendReqAsync(string username, string bookname) {
            this.SendReqAsync(username, bookname, null);
        }
        
        /// <remarks/>
        public void SendReqAsync(string username, string bookname, object userState) {
            if ((this.SendReqOperationCompleted == null)) {
                this.SendReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendReqOperationCompleted);
            }
            this.InvokeAsync("SendReq", new object[] {
                        username,
                        bookname}, this.SendReqOperationCompleted, userState);
        }
        
        private void OnSendReqOperationCompleted(object arg) {
            if ((this.SendReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendReqCompleted(this, new SendReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ShowAllReq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        public IssueBooks[] ShowAllReq() {
            object[] results = this.Invoke("ShowAllReq", new object[0]);
            return ((IssueBooks[])(results[0]));
        }
        
        /// <remarks/>
        public void ShowAllReqAsync() {
            this.ShowAllReqAsync(null);
        }
        
        /// <remarks/>
        public void ShowAllReqAsync(object userState) {
            if ((this.ShowAllReqOperationCompleted == null)) {
                this.ShowAllReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowAllReqOperationCompleted);
            }
            this.InvokeAsync("ShowAllReq", new object[0], this.ShowAllReqOperationCompleted, userState);
        }
        
        private void OnShowAllReqOperationCompleted(object arg) {
            if ((this.ShowAllReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowAllReqCompleted(this, new ShowAllReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteBookFromLib", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteBookFromLib([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Location, out bool DeleteBookFromLibResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteBookFromLibResultSpecified) {
            object[] results = this.Invoke("DeleteBookFromLib", new object[] {
                        name,
                        Location});
            DeleteBookFromLibResult = ((bool)(results[0]));
            DeleteBookFromLibResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteBookFromLibAsync(string name, string Location) {
            this.DeleteBookFromLibAsync(name, Location, null);
        }
        
        /// <remarks/>
        public void DeleteBookFromLibAsync(string name, string Location, object userState) {
            if ((this.DeleteBookFromLibOperationCompleted == null)) {
                this.DeleteBookFromLibOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteBookFromLibOperationCompleted);
            }
            this.InvokeAsync("DeleteBookFromLib", new object[] {
                        name,
                        Location}, this.DeleteBookFromLibOperationCompleted, userState);
        }
        
        private void OnDeleteBookFromLibOperationCompleted(object arg) {
            if ((this.DeleteBookFromLibCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteBookFromLibCompleted(this, new DeleteBookFromLibCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateQuantity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Location, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string quantity, out bool UpdateQuantityResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateQuantityResultSpecified) {
            object[] results = this.Invoke("UpdateQuantity", new object[] {
                        name,
                        Location,
                        quantity});
            UpdateQuantityResult = ((bool)(results[0]));
            UpdateQuantityResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void UpdateQuantityAsync(string name, string Location, string quantity) {
            this.UpdateQuantityAsync(name, Location, quantity, null);
        }
        
        /// <remarks/>
        public void UpdateQuantityAsync(string name, string Location, string quantity, object userState) {
            if ((this.UpdateQuantityOperationCompleted == null)) {
                this.UpdateQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateQuantityOperationCompleted);
            }
            this.InvokeAsync("UpdateQuantity", new object[] {
                        name,
                        Location,
                        quantity}, this.UpdateQuantityOperationCompleted, userState);
        }
        
        private void OnUpdateQuantityOperationCompleted(object arg) {
            if ((this.UpdateQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateQuantityCompleted(this, new UpdateQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/forgetpassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void forgetpassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string question, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string answer, out bool forgetpasswordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool forgetpasswordResultSpecified) {
            object[] results = this.Invoke("forgetpassword", new object[] {
                        username,
                        question,
                        answer});
            forgetpasswordResult = ((bool)(results[0]));
            forgetpasswordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void forgetpasswordAsync(string username, string question, string answer) {
            this.forgetpasswordAsync(username, question, answer, null);
        }
        
        /// <remarks/>
        public void forgetpasswordAsync(string username, string question, string answer, object userState) {
            if ((this.forgetpasswordOperationCompleted == null)) {
                this.forgetpasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnforgetpasswordOperationCompleted);
            }
            this.InvokeAsync("forgetpassword", new object[] {
                        username,
                        question,
                        answer}, this.forgetpasswordOperationCompleted, userState);
        }
        
        private void OnforgetpasswordOperationCompleted(object arg) {
            if ((this.forgetpasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.forgetpasswordCompleted(this, new forgetpasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/registration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registration([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string q, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string a) {
            this.Invoke("registration", new object[] {
                        username,
                        password,
                        q,
                        a});
        }
        
        /// <remarks/>
        public void registrationAsync(string username, string password, string q, string a) {
            this.registrationAsync(username, password, q, a, null);
        }
        
        /// <remarks/>
        public void registrationAsync(string username, string password, string q, string a, object userState) {
            if ((this.registrationOperationCompleted == null)) {
                this.registrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrationOperationCompleted);
            }
            this.InvokeAsync("registration", new object[] {
                        username,
                        password,
                        q,
                        a}, this.registrationOperationCompleted, userState);
        }
        
        private void OnregistrationOperationCompleted(object arg) {
            if ((this.registrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isvaliduser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isvaliduser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isvaliduserResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isvaliduserResultSpecified) {
            object[] results = this.Invoke("isvaliduser", new object[] {
                        username,
                        password});
            isvaliduserResult = ((bool)(results[0]));
            isvaliduserResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isvaliduserAsync(string username, string password) {
            this.isvaliduserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isvaliduserAsync(string username, string password, object userState) {
            if ((this.isvaliduserOperationCompleted == null)) {
                this.isvaliduserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisvaliduserOperationCompleted);
            }
            this.InvokeAsync("isvaliduser", new object[] {
                        username,
                        password}, this.isvaliduserOperationCompleted, userState);
        }
        
        private void OnisvaliduserOperationCompleted(object arg) {
            if ((this.isvaliduserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isvaliduserCompleted(this, new isvaliduserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isvalidAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isvalidAdmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isvalidAdminResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isvalidAdminResultSpecified) {
            object[] results = this.Invoke("isvalidAdmin", new object[] {
                        username,
                        password});
            isvalidAdminResult = ((bool)(results[0]));
            isvalidAdminResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isvalidAdminAsync(string username, string password) {
            this.isvalidAdminAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isvalidAdminAsync(string username, string password, object userState) {
            if ((this.isvalidAdminOperationCompleted == null)) {
                this.isvalidAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisvalidAdminOperationCompleted);
            }
            this.InvokeAsync("isvalidAdmin", new object[] {
                        username,
                        password}, this.isvalidAdminOperationCompleted, userState);
        }
        
        private void OnisvalidAdminOperationCompleted(object arg) {
            if ((this.isvalidAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isvalidAdminCompleted(this, new isvalidAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/resetpassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void resetpassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            this.Invoke("resetpassword", new object[] {
                        username,
                        password});
        }
        
        /// <remarks/>
        public void resetpasswordAsync(string username, string password) {
            this.resetpasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void resetpasswordAsync(string username, string password, object userState) {
            if ((this.resetpasswordOperationCompleted == null)) {
                this.resetpasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetpasswordOperationCompleted);
            }
            this.InvokeAsync("resetpassword", new object[] {
                        username,
                        password}, this.resetpasswordOperationCompleted, userState);
        }
        
        private void OnresetpasswordOperationCompleted(object arg) {
            if ((this.resetpasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetpasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ShowAllBooksLib", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        public Book[] ShowAllBooksLib() {
            object[] results = this.Invoke("ShowAllBooksLib", new object[0]);
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void ShowAllBooksLibAsync() {
            this.ShowAllBooksLibAsync(null);
        }
        
        /// <remarks/>
        public void ShowAllBooksLibAsync(object userState) {
            if ((this.ShowAllBooksLibOperationCompleted == null)) {
                this.ShowAllBooksLibOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowAllBooksLibOperationCompleted);
            }
            this.InvokeAsync("ShowAllBooksLib", new object[0], this.ShowAllBooksLibOperationCompleted, userState);
        }
        
        private void OnShowAllBooksLibOperationCompleted(object arg) {
            if ((this.ShowAllBooksLibCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowAllBooksLibCompleted(this, new ShowAllBooksLibCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ShowAllBooksMar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        public Book[] ShowAllBooksMar() {
            object[] results = this.Invoke("ShowAllBooksMar", new object[0]);
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void ShowAllBooksMarAsync() {
            this.ShowAllBooksMarAsync(null);
        }
        
        /// <remarks/>
        public void ShowAllBooksMarAsync(object userState) {
            if ((this.ShowAllBooksMarOperationCompleted == null)) {
                this.ShowAllBooksMarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowAllBooksMarOperationCompleted);
            }
            this.InvokeAsync("ShowAllBooksMar", new object[0], this.ShowAllBooksMarOperationCompleted, userState);
        }
        
        private void OnShowAllBooksMarOperationCompleted(object arg) {
            if ((this.ShowAllBooksMarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowAllBooksMarCompleted(this, new ShowAllBooksMarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SearchBookFromLib", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        public Book[] SearchBookFromLib([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("SearchBookFromLib", new object[] {
                        name});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchBookFromLibAsync(string name) {
            this.SearchBookFromLibAsync(name, null);
        }
        
        /// <remarks/>
        public void SearchBookFromLibAsync(string name, object userState) {
            if ((this.SearchBookFromLibOperationCompleted == null)) {
                this.SearchBookFromLibOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchBookFromLibOperationCompleted);
            }
            this.InvokeAsync("SearchBookFromLib", new object[] {
                        name}, this.SearchBookFromLibOperationCompleted, userState);
        }
        
        private void OnSearchBookFromLibOperationCompleted(object arg) {
            if ((this.SearchBookFromLibCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchBookFromLibCompleted(this, new SearchBookFromLibCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SearchBookFromMar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        public Book[] SearchBookFromMar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("SearchBookFromMar", new object[] {
                        name});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchBookFromMarAsync(string name) {
            this.SearchBookFromMarAsync(name, null);
        }
        
        /// <remarks/>
        public void SearchBookFromMarAsync(string name, object userState) {
            if ((this.SearchBookFromMarOperationCompleted == null)) {
                this.SearchBookFromMarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchBookFromMarOperationCompleted);
            }
            this.InvokeAsync("SearchBookFromMar", new object[] {
                        name}, this.SearchBookFromMarOperationCompleted, userState);
        }
        
        private void OnSearchBookFromMarOperationCompleted(object arg) {
            if ((this.SearchBookFromMarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchBookFromMarCompleted(this, new SearchBookFromMarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class IssueBooks {
        
        private string bookName1Field;
        
        private string userName1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookName1 {
            get {
                return this.bookName1Field;
            }
            set {
                this.bookName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName1 {
            get {
                return this.userName1Field;
            }
            set {
                this.userName1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class Book {
        
        private string locationField;
        
        private string nameField;
        
        private string priceField;
        
        private string quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddBooksToMarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteBookFromMarCompletedEventHandler(object sender, DeleteBookFromMarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteBookFromMarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteBookFromMarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteBookFromMarResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteBookFromMarResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddBookToLibCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IssueBookCompletedEventHandler(object sender, IssueBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IssueBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IssueBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IssueBookResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IssueBookResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendReqCompletedEventHandler(object sender, SendReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SendReqResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SendReqResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ShowAllReqCompletedEventHandler(object sender, ShowAllReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowAllReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowAllReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IssueBooks[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IssueBooks[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteBookFromLibCompletedEventHandler(object sender, DeleteBookFromLibCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteBookFromLibCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteBookFromLibCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteBookFromLibResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteBookFromLibResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateQuantityCompletedEventHandler(object sender, UpdateQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool UpdateQuantityResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool UpdateQuantityResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void forgetpasswordCompletedEventHandler(object sender, forgetpasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class forgetpasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal forgetpasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool forgetpasswordResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool forgetpasswordResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void registrationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void isvaliduserCompletedEventHandler(object sender, isvaliduserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isvaliduserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isvaliduserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isvaliduserResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isvaliduserResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void isvalidAdminCompletedEventHandler(object sender, isvalidAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isvalidAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isvalidAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isvalidAdminResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isvalidAdminResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void resetpasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ShowAllBooksLibCompletedEventHandler(object sender, ShowAllBooksLibCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowAllBooksLibCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowAllBooksLibCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ShowAllBooksMarCompletedEventHandler(object sender, ShowAllBooksMarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowAllBooksMarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowAllBooksMarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchBookFromLibCompletedEventHandler(object sender, SearchBookFromLibCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchBookFromLibCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchBookFromLibCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchBookFromMarCompletedEventHandler(object sender, SearchBookFromMarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchBookFromMarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchBookFromMarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591